### ISSUE TITLE
CRAM support

### ISSUE THREAD

**Issue by jjfarrell** [kehrlab/PopDel#11]
Are there plans for cram support?  

As a workaround, could a cram be piped into PopDel using samtools?

samtools view  -T ref38.fa  -b myBam1.cram |popdel profile -

**Comment by serosko** [comment]
Hi,
actually, there is already an experimental, HTSlib-based, version of PopDel which supports CRAM files.
I am planning to release it very soon. 
Your workaround using samtools view piped into PopDel will not work, because PopDel requires the index of the BAM file.
If you are interested in using it before the release, I can send you the source code or a binary.

**Comment by serosko** [comment]
I just published version [1.3.0](https://github.com/kehrlab/PopDel/releases/tag/v1.3.0) of PopDel with added CRAM support.

**Comment by jjfarrell** [comment]
Thanks! I will try out the new version.
