### ISSUE TITLE
Issue with multiple read groups per sample

### ISSUE THREAD

**Issue by holtgrewe** [kehrlab/PopDel#3]
I'm having a BAM file that has the following read group structure, as per GATK best practices, one for each lane. This is only relevant for correcting lane biases in yield, though, and probably irrelevant for any HiSeq X era analysis...

```
@RG     ID:sample-N1-DNA1-WGS1.0       SM:sample-N1-DNA1-WGS1 PL:ILLUMINA
@RG     ID:sample-N1-DNA1-WGS1.1       SM:sample-N1-DNA1-WGS1 PL:ILLUMINA
@RG     ID:sample-N1-DNA1-WGS1.2       SM:sample-N1-DNA1-WGS1 PL:ILLUMINA
```

PopDel dislikes my BAM file:

```
[PopDel] Not enough reads in sampling regions for read group(s) 'sample-N1-DNA1-WGS1.2'. Please use different sampling intervals (option '-i') or use the option '-n'
```

A suitable workaround would be to either assume one sample per BAM file or not gathering reads by read group but rather by sample.

**Comment by serosko** [comment]
Combining the counts of the read groups per default might not be suited if there really is a difference in the different read groups (e.g. the mentioned lane bias). Therefore, PopDel computes the background distribution of the insert sizes per read group. To get a smooth estimate of the real distribution this requires some reads. The default threshold of 50,000 read-pairs per read group can be modified with the option '-n'. But normally it is already quite lax, because it is applied across all sampling intervals: All combined default sampling intervals on GRCh38 have a total length of 22,000,000bp. Assuming an insert size of ~300bp this translates to a minimum per read group read coverage of ~0.68. 
The best option in your case would probably be to increase the size of the sampling intervals (-i), so you get enough reads for a smooth estimate of the insert size distribution. The other option is to reduce the treshold (-n), but this might hurt subsequent steps if the estimated distribution gets too rough.
We will discuss if another option for combining the read groups of one sample like you suggested would be a good feature.

**Comment by holtgrewe** [comment]
As a side note, the insert size bias depends on the library but not the lane. The read groups are only meaningful when sequencing more than one library. This case will be rare as usually more library than sequenced is prepared in case of low yield such that sequencing but not library preparation has to be repeated.

**Comment by holtgrewe** [comment]
Also, using a [robust standard estimation approach](https://en.wikipedia.org/wiki/Robust_measures_of_scale) would make the estimation of the standard deviation depend less critically on the selection of a good interval set.

**Comment by serosko** [comment]
For the creation of the histogram itself we probably cannot change much because it is basically counting insert sizes and subsequent smoothing, but something like the median absolute deviation might be a good alternative to the standard deviation. We will look into it.

**Comment by bkehr** [comment]
We have put effort into implementing the parameter estimation per read group and not just per sample because of our experience that BAM files can - in rare cases - contain reads from different libraries with different insert size distributions. These differences in insert sizes heavily affect PopDel's calling. The separate computation of insert sizes per library is necessary in the general case. We used read groups instead of libraries since read groups are more commonly correctly specified in the BAM file and a read group usually does not contain reads from different libraries.

It is correct that we were not expecting read groups with a coverage below 1X. In such special cases, please use the -i option to increase the total size of the sampling intervals as Sebastian suggested.

Apart from estimating the standard deviation/MAD/... of the insert sizes from the interval set, we also estimate the entire insert size distribution. PopDel uses the empirical insert size distribution in the computation of genotype likelihoods. A minimum number of reads is necessary to estimate a reasonably good distribution. To keep this number small, we require the intervals to be reasonably well selected.

**Comment by holtgrewe** [comment]
I agree that the default behaviour is sane but it would be useful to have a parameter to override this behaviour. I've now gone to 5M intervals on the chromosomes (in theory I'd have to validate all of them for mapability) and I'm still getting popdel failures. This is not practical.

Having a "squash read groups to samples" flag would allow me to do `popdel sample ... || popdel sample --squash-read-groups` to retry after failure.

I'd be willing to submit a patch if you're not opposed to this.

**Comment by serosko** [comment]
If you find the time for it and want to contribute a patch, this would be appreciated.

**Comment by serosko** [comment]
Introduced read group merging (option '-mrg') in version [1.1.0](https://github.com/kehrlab/PopDel/tree/v1.1.0).
