### ISSUE TITLE
error message in popdel

### ISSUE THREAD

**Issue by Martaprf** [kehrlab/PopDel#5]
I am trying run popdel profile with the follow comand :
popdel profile sample_sorted.bam
but i get this error:
- Profile creation from BAM-file
=================================

[PopDel 2019-04-16 11:08:57] Command:

sample_sorted.bam

[PopDel 2019-04-16 11:08:57] Found 1 read groups in input bam file 'sample_sorted.bam'.
[PopDel 2019-04-16 11:08:57] Reference consists of 195 sequences with a total length of 3099922541 base pairs.
terminate called after throwing an instance of 'std::ios_base::failure[abi:cxx11]'
  what():  [ERROR] [PopDel] Not enough reads in sampling regions for read group(s) 'id'. Please use different sampling intervals (option '-i') or use the option '-n' to reduce the number of required read pairs for each histogram of each read group.: iostream error
Aborted

Cam someone help me with this?

Thanks

**Comment by serosko** [comment]
Hi, 
it looks like your bam file does not have enough reads in  the sampling regions.
Here is what you can do:
- First, check if your chromosome/contig names are exactly as in the list of sampling regions [(readme)](https://github.com/kehrlab/PopDel#10---sampling-intervals-for-profile-parameter-estimation). If your reference is not GRCh38, they might be different.
- If they are different, use a custom list of sampling regions (described in the chapter as the point above)
- PopDel only requires a very moderate amount of reads for sampling (default 50,000 read pairs.). Make sure that your BAM-file actually contains sufficient reads in at least one of the sampling regions. Is your BAM-file supposed to have alignments for the whole genome, or only for as small area? In latter case, adapt the sampling regions to match your BAM-file.
- Lowering the threshold (-n) for the sampling reads should only be done as a last resort and if you are 100% sure that your BAM-file and the sampling regions are ok, because sampling without sufficient reads might have a negative impact on later steps.

If this does not help, feel free to ask again.

**Comment by serosko** [comment]
I just realised that your read group is called 'id'. Are you sure your BAM-file is allright?

**Comment by Martaprf** [comment]
I am new in this type of analysis and I am trying some tools, and i searched a lot for try understand what i should put in here ( -R "@RG\tID:id\tSM:sample\tLB:lib"), but I did not find anything .... You can explain me what it means and what i should put here?

Because if i put the option -n 8000 this command works but in the call command i have another error.

Thanks so much for your help!

**Comment by serosko** [comment]
I see,
there is not strict rule for what to put in there as long as the ID is unique. Normally, the read group indicates that the reads were generated during the same run of the sequencer. [This](https://gatkforums.broadinstitute.org/gatk/discussion/6472/read-groups) post in the GATK-forums describes this quite well. If your bam file is the only one you are working with and you just want to try out some things, it should be ok to just call the read group 'id'. But if you are adding more bam files to your analyses, there will be conflicts. I suggest that you give each of your sample a unique name (e.g "S01" for the first sample and so on) and just call the read group of that sample "S01.1".  This will avoid later conflicts. 
But this is most likely not the cause of the problem you are facing with popdel.
How do the first 3 lines you get with the following command look?
`samtools view -H sample_sorted.bam`

**Comment by Martaprf** [comment]
samtools view -H sample_sorted.bam
@HD     VN:1.3  SO:coordinate
@SQ     SN:chr1 LN:248956422
@SQ     SN:chr2 LN:242193529

**Comment by serosko** [comment]
The contig names are ok.
Let's try to check the average coverage of your BAM-file in one of the sampling regions. Try
`samtools depth sample_sorted.bam -r chr1:35000000-36000000 | awk '{i+=$3;j++}END{print i/j}'`
What number do you get?

**Comment by Martaprf** [comment]
samtools depth sample_sorted.bam -r chr1:35000000-36000000 | awk '{i+=$3;j++}END{print i/j}'
1.84974

**Comment by serosko** [comment]
That is some really low coverage you have there. I doubt that it will be possible to do adequate variant calling with that. Normally I would expect the coverage to be more in the range of 10-30, depending on your experimental setup etc. What type of data are you using? Is it supposed to be whole genome, whole exome, only one chromosome? How did you generate it? Was it some sequencing done at your institution, or did you download some publicly available reads and mapped them?

**Comment by Martaprf** [comment]
I have samples of target sequencing for some selected genes. I tryed the command of coverage for on this genes and the results was:

samtools depth sample_sorted.bam -r chr5:112707498-112846239| awk '{i+=$3;j++}END{print i/j}'
244.44

I think that I should alter the sampling regions for the regions in the target sequencing using the -i option. You think this correct?

Thank you a lot for your help!

**Comment by serosko** [comment]
Ah, than that is the reason. 
Unfortunately, PopDel was designed for whole genome sequencing, not exome or targeted sequencing.
So, if you change the sampling regions to the genes using the -i option and select the regions of interest (like described in the second example of [this](https://github.com/kehrlab/PopDel#4---running-popdel-profile) chapter of the readme) to match your selected genes, PopDel profile should run.
But because PopDel was not designed and tested  for targeted sequencing and I have no experience with it, I cannot guarantee that PopDel call will deliver reliable results or help you with handling the data.
If you still want to try it anyway, consider also using the -r option (described [here](https://github.com/kehrlab/PopDel#5---running-popdel-call), second example of sub-section 5.4) to match your targeted genes. But, as already mentioned, I cannot guarantee any sensible results, because I don't know if the behaviour of targeted sequencing data violates PopDel's expectations. 
If you get any results (positive or negative), please share your experience here, so I know how PopDel behaves on that kind of data for future reference.

**Comment by Martaprf** [comment]
Ok, I will try and when I obtained some results I tell her!

Thanks for your help, it was essential!
